<?php
require_once __DIR__.'/../includes/config.php';
if (!isset($_SESSION['role']) || ($_SESSION['role']!=='admin' && $_SESSION['role']!=='placement_officer')){header('Location:login.php');exit;}
// Select all shortlisted internship applications
$apps=$mysqli->query("SELECT ia.id as app_id, ia.student_id, ia.internship_id, ia.application_status, u.full_name, u.email, io.company, io.role FROM internship_applications ia JOIN users u ON u.id=ia.student_id JOIN internship_opportunities io ON io.id=ia.internship_id WHERE ia.application_status='Shortlisted' ORDER BY ia.applied_at");
// On POST: add interview round
if($_SERVER['REQUEST_METHOD']==='POST' && !empty($_POST['app_id'])){
  $st=$mysqli->prepare("INSERT INTO internship_interviews (internship_application_id, student_id, company, internship_role, scheduled_at, panel_details, status) VALUES (?,?,?,?,?,?, 'scheduled')");
  $st->bind_param('iissss',$_POST['app_id'],$_POST['student_id'],$_POST['company'],$_POST['role'],$_POST['date'],$_POST['panel']);
  $st->execute(); $st->close(); header('Location: schedule_internship_interviews.php'); exit;
}
// List all scheduled interviews
$sched=$mysqli->query("SELECT ii.*,u.full_name FROM internship_interviews ii LEFT JOIN users u ON u.id=ii.student_id WHERE ii.status='scheduled' ORDER BY ii.scheduled_at");
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Schedule Internship Interviews</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"><style>body{background:#f4f7fa;font-family:'Inter',sans-serif;}.main{max-width:1100px;margin:38px auto;background:white;border-radius:12px;padding:32px;box-shadow:0 2px 14px rgba(31,59,91,.09);}h2{margin-top:4px;color:#1d3557;}form{margin-bottom:24px;border-bottom:1px solid #f3f3f3;padding-bottom:22px;}label{display:block;margin-top:14px;font-weight:600;}.row{margin-bottom:12px;display:flex;gap:22px;align-items:center;}input,select{padding:8px 10px;border-radius:7px;border:1.5px solid #bcd;}</style></head><body><div class='main'><h2><i class='fas fa-calendar-alt'></i> Schedule Internship Interviews</h2><form method="post"><div class="row"><label>Shortlisted Application: <select name="app_id" required><option value=''>Select...</option><?php while($a=$apps&&$apps->fetch_assoc()):?><option value="<?=$a['app_id']?>"><?=$a['company']?> (<?=$a['role']?>) - <?=$a['full_name']?></option><?php endwhile;?></select></label><label>Date/Time:<input name="date" type="datetime-local" required></label><label>Panel Name(s): <input name="panel" required></label><input type="hidden" name="student_id" value="<?php echo isset($a['student_id'])?$a['student_id']:'';?>"><input type="hidden" name="company" value="<?php echo isset($a['company'])?$a['company']:'';?>"><input type="hidden" name="role" value="<?php echo isset($a['role'])?$a['role']:'';?>"></div><button type="submit">Add Interview</button></form><h3 style="margin-top:36px;"><i class='fa fa-clock'></i> Scheduled Interviews</h3><table style="width:100%;background:#fafbfc;margin-top:8px;border-radius:9px;"><tr><th>Internship</th><th>Student</th><th>Date/Time</th><th>Panel</th><th>Status</th></tr><?php while($row=$sched&&$sched->fetch_assoc()):?><tr><td><?=htmlspecialchars($row['company'].' – '.$row['internship_role'])?></td><td><?=htmlspecialchars($row['full_name'])?></td><td><?=htmlspecialchars($row['scheduled_at'])?></td><td><?=htmlspecialchars($row['panel_details'])?></td><td><?=htmlspecialchars($row['status'])?></td></tr><?php endwhile;?></table></div></body></html>
